//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSIntegration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSIntegration.Resources.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding items to project {0}.
        /// </summary>
        public static string ErrorAddingItemsToProject {
            get {
                return ResourceManager.GetString("ErrorAddingItemsToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding project {0}.
        /// </summary>
        public static string ErrorAddingProject {
            get {
                return ResourceManager.GetString("ErrorAddingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding references between projects.
        /// </summary>
        public static string ErrorAddingReferencesBetweenProjects {
            get {
                return ResourceManager.GetString("ErrorAddingReferencesBetweenProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding sdks to project {0}..
        /// </summary>
        public static string ErrorAddingSdksToProject {
            get {
                return ResourceManager.GetString("ErrorAddingSdksToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string ErrorDialogShowDetails {
            get {
                return ResourceManager.GetString("ErrorDialogShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong :-(.
        /// </summary>
        public static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Requirement Type {0}.
        /// </summary>
        public static string ErrorInvalidRequirementType {
            get {
                return ResourceManager.GetString("ErrorInvalidRequirementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install-Package -Id {0} -Version {1}.
        /// </summary>
        public static string ErrorMissingNugetPackagesInstallTemplate {
            get {
                return ResourceManager.GetString("ErrorMissingNugetPackagesInstallTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some NuGet packages could not be added to your project {0}. This could have been caused if you were offline. 
        ///Please verify the following list of packages needed by your project&apos;s code and manually add the missing packages: 
        ///
        ///{1}.
        /// </summary>
        public static string ErrorMissingNugetPackagesTemplate {
            get {
                return ResourceManager.GetString("ErrorMissingNugetPackagesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find project {0}.
        /// </summary>
        public static string ErrorUnableGetProjectByPath {
            get {
                return ResourceManager.GetString("ErrorUnableGetProjectByPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open project overview..
        /// </summary>
        public static string ErrorUnableToOpenProjectOverview {
            get {
                return ResourceManager.GetString("ErrorUnableToOpenProjectOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set default solution configuration.
        /// </summary>
        public static string ErrorUnableToSetDefaultConfiguration {
            get {
                return ResourceManager.GetString("ErrorUnableToSetDefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error collapsing the solution tree. Ex:.
        /// </summary>
        public static string ErrorVsGenShellCollapseSolutionItemsMessage {
            get {
                return ResourceManager.GetString("ErrorVsGenShellCollapseSolutionItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error showing status message. Ex:.
        /// </summary>
        public static string ErrorVsGenShellShowStatusBarMessageMessage {
            get {
                return ResourceManager.GetString("ErrorVsGenShellShowStatusBarMessageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} to project ....
        /// </summary>
        public static string StatusAddingItem {
            get {
                return ResourceManager.GetString("StatusAddingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding NuGet package {0} to project ....
        /// </summary>
        public static string StatusAddingNuget {
            get {
                return ResourceManager.GetString("StatusAddingNuget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding project {0} to solution....
        /// </summary>
        public static string StatusAddingProject {
            get {
                return ResourceManager.GetString("StatusAddingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding references between projects....
        /// </summary>
        public static string StatusAddingProjectReferences {
            get {
                return ResourceManager.GetString("StatusAddingProjectReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Windows Template Studio project....
        /// </summary>
        public static string StatusBarCreatingProject {
            get {
                return ResourceManager.GetString("StatusBarCreatingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation finished.
        /// </summary>
        public static string StatusBarGenerationFinished {
            get {
                return ResourceManager.GetString("StatusBarGenerationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new feature cancelled.
        /// </summary>
        public static string StatusBarNewItemAddFeatureCancelled {
            get {
                return ResourceManager.GetString("StatusBarNewItemAddFeatureCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature {0} successfully added.
        /// </summary>
        public static string StatusBarNewItemAddFeatureSuccess {
            get {
                return ResourceManager.GetString("StatusBarNewItemAddFeatureSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new page cancelled.
        /// </summary>
        public static string StatusBarNewItemAddPageCancelled {
            get {
                return ResourceManager.GetString("StatusBarNewItemAddPageCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} successfully added.
        /// </summary>
        public static string StatusBarNewItemAddPageSuccess {
            get {
                return ResourceManager.GetString("StatusBarNewItemAddPageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new service cancelled.
        /// </summary>
        public static string StatusBarNewItemAddServiceCancelled {
            get {
                return ResourceManager.GetString("StatusBarNewItemAddServiceCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} successfully added.
        /// </summary>
        public static string StatusBarNewItemAddServiceSuccess {
            get {
                return ResourceManager.GetString("StatusBarNewItemAddServiceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new testing project cancelled.
        /// </summary>
        public static string StatusBarNewItemAddTestingCancelled {
            get {
                return ResourceManager.GetString("StatusBarNewItemAddTestingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing project {0} successfully added.
        /// </summary>
        public static string StatusBarNewItemAddTestingSuccess {
            get {
                return ResourceManager.GetString("StatusBarNewItemAddTestingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Template Studio.
        /// </summary>
        public static string WindowsTemplateStudio {
            get {
                return ResourceManager.GetString("WindowsTemplateStudio", resourceCulture);
            }
        }
    }
}
